---
title: "Data Manipulation"
output: github_document
---



```{r setup}
library(tidyverse)
library(readxl)
library(haven)
```

Read in the litters datasets.

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df) 
```

```{r}
pipe_df = read.csv("./data/FAS_pups.csv")
pipe_df = janitor::clean_names(pipe_df) 
```


## select
`select` is used to select columns.

```{r}
select(litters_df, group, litter_number,gd0_weight)

select(litters_df, gd0_weight, group)

select(litters_df, group, gd0_weight:gd_of_birth)

select(litters_df, group, starts_with("pups"))

select(litters_df, -litter_number)

select(litters_df, group, -starts_with("gd"))

select(litters_df, group, litter_id = litters_number)

select(litters_df, group, litter_id = litters_number, everything())

select(litters_df,gd0_weight, everything())
```

*you can use select to rename a variable, and use select to rename a variable and keep everything else

*difference between select and pull 
*the above code chunck didn't save anything we selec. If we do litters_df = select(), it will save. 

# `filter`

get rid of rows using filter()

```{r}
filter(litters_df, group == "con7")

filter(litters_df, group == "Mod8")

filter(litters_df, group != "con7")

filter(litters_df, gd0_weight > 20)

filter(litters_df, gd0_weight <= 20)

filter(litters_df, group == "con7" | gourp = "con8")

filter(litters_df, group != "con7" | gourp = "con8")

```

